config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :gateway do
    get '/:gateway_id/ebsin/:order_id' => 'ebsin#show',     :as => :ebsin
    get '/ebsin/:id/comeback'          => 'ebsin#comeback', :as => :ebsin_comeback
  end
end

app/models/payment_method/ebsin.rb
class PaymentMethod::Ebsin < Spree::PaymentMethod

  preference :account_id, :string
  preference :url,        :string, :default =>  "https://secure.ebs.in/pg/ma/sale/pay/"
  preference :secret_key, :string
  preference :mode, :string
  preference :currency_code, :string

  attr_accessible :preferred_account_id, :preferred_url, :preferred_secret_key, :preferred_mode, :preferred_currency_code

  def payment_profiles_supported?
    false
  end
  
  def payment_source_class
    Ebsinfo
  end

end

app/models/spree/ebsinfo.rb
module Spree
  class Ebsinfo < ActiveRecord::Base
    attr_accessible :first_name, :last_name, :TransactionId, :PaymentId, :amount, :order_id
    self.table_name = :ebsinfos

    has_many :payments, :as => :source

    def actions
      %w{mark_as_captured void}
    end

    # Indicates whether its possible to capture the payment
    def can_mark_as_captured?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def mark_as_captured(payment)
      payment.update_attribute(:state, 'pending') if payment.state == 'checkout'
      payment.complete
      true
    end

    def void(payment)
      payment.update_attribute(:state, 'pending') if payment.state == 'checkout'
      payment.void
      true
    end
  end
end

app/models/spree/payment_method/ebsin.rb
class Spree::PaymentMethod::Ebsin < Spree::PaymentMethod
  attr_accessible :preferred_account_id, :preferred_url, :preferred_secret_key, :preferred_mode, :preferred_currency_code

  preference :account_id, :string
  preference :url,        :string, :default =>  "https://secure.ebs.in/pg/ma/sale/pay/"
  preference :secret_key, :string
  preference :mode, :string
  preference :currency_code, :string

  attr_accessible :preferred_account_id, :preferred_url, :preferred_secret_key, :preferred_mode, :preferred_currency_code

  def payment_profiles_supported?
    false
  end

  def payment_source_class
    Ebsinfo
  end

end

app/controllers/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do

  before_filter :redirect_for_ebsin, :only => :update

  private

  def redirect_for_ebsin
    return unless params[:state] == "payment"
    @payment_method = Spree::PaymentMethod.find(params[:order][:payments_attributes].first[:payment_method_id])
    if @payment_method && @payment_method.kind_of?(PaymentMethod::Ebsin)
      #@order.update_attributes(object_params)
      redirect_to gateway_ebsin_path(:gateway_id => @payment_method.id, :order_id => @order.id)
      #redirect_to "/gateway/"+@payment_method.id.to_s+"/ebsin/"+@order.id.to_s
    end
  end

end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do

  before_filter :redirect_for_ebsin, :only => :update

  private

    def redirect_for_ebsin
      return unless params[:state] == "payment"
      @payment_method = Spree::PaymentMethod.find(params[:order][:payments_attributes].first[:payment_method_id])
      if @payment_method && @payment_method.kind_of?(Spree::PaymentMethod::Ebsin)
        @order.update_attributes(object_params)
        redirect_to gateway_ebsin_path(:gateway_id => @payment_method.id, :order_id => @order.id)
      end
    end
end

app/controllers/spree/gateway/ebsin_controller.rb
require 'base64'
require 'digest/md5'
require 'ruby_rc4'

module Spree
  class Gateway::EbsinController < Spree::StoreController
    include Spree::Core::ControllerHelpers::Order
    include Spree::Core::ControllerHelpers::Auth
    include ERB::Util
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/products'

    respond_to :html

    skip_before_filter :verify_authenticity_token, :only => [:comeback]

    NECESSARY = [
                 "Mode",
                 "PaymentID",
                 "DateCreated",
                 "MerchantRefNo",
                 "Amount",
                 "TransactionID",
                 "ResponseCode",
                 "ResponseMessage"
                ]

  # Result from EBS
  #
  def comeback
    @order   = current_order #Spree::Order.find_by_id(params[:id])
    @gateway = @order && @order.payments.first.payment_method
    #@gateway && @gateway.kind_of?(PaymentMethod::Ebsin) && params[:DR]
    @data = ebsin_decode(params[:DR], @gateway.preferred_secret_key)
    if  (@data) &&
        (@data["ResponseMessage"] == "Transaction Successful") &&
        (@data["ResponseCode"] == "0") &&
        (@data["MerchantRefNo"] == @order.number.to_s) &&
        (@data["Amount"].to_f == @order.outstanding_balance.to_f)

      #puts(@data)
      ebsin_payment_success(@data)

      @order.update_attributes({:state => "complete", :completed_at => Time.now}, :without_protection => true)

      session[:order_id] = nil

      @order.finalize!
      flash[:commerce_tracking] = "nothing special"
      redirect_to order_url(@order, {:checkout_complete => true, :token => @order.token}), :notice => I18n.t("payment_success")
    else
      ebs_error = @data["ResponseMessage"]
      flash[:error] = I18n.t("ebsin_payment_response_error")+" Payment: "+ebs_error
      redirect_to (@order.blank? ? root_url : edit_order_url(@order, {:token => @order.token}))
    end
  end

    # Result from EBS
    #
    def comeback
      @order   = current_order #Spree::Order.find_by_id(params[:id])
      @gateway = @order && @order.payments.first.payment_method
      #@gateway && @gateway.kind_of?(PaymentMethod::Ebsin) && params[:DR]
      @data = ebsin_decode(params[:DR], @gateway.preferred_secret_key)
      if  (@data) &&
          (@data["ResponseMessage"] == "Transaction Successful") &&
          (@data["ResponseCode"] == "0") &&
          (@data["MerchantRefNo"] == @order.number.to_s) &&
          (@data["Amount"].to_f == @order.outstanding_balance.to_f)

        ebsin_payment_success(@data)

        @order.reload
        @order.next

        session[:order_id] = nil

        @order.finalize!
        redirect_to order_url(@order, {:checkout_complete => true, :token => @order.token}), :notice => I18n.t("payment_success")
      else
        ebs_error = @data["ResponseMessage"]
        flash[:error] = I18n.t("ebsin_payment_response_error")+" Payment: "+ebs_error
        redirect_to (@order.blank? ? root_url : edit_order_url(@order, {:token => @order.token}))
      end

    end


    private

    # processing geteway returned data
    #
    def ebsin_decode(data, key)
      rc4 = RubyRc4.new(key)
      (Hash[ rc4.encrypt(Base64.decode64(data.gsub(/ /,'+'))).split('&').map { |x| x.split("=") } ]).slice(* NECESSARY )
    end

    # Completed payment process
    #
    def ebsin_payment_success(data)
      # record the payment
      source = Spree::Ebsinfo.create(:first_name => @order.bill_address.firstname, :last_name => @order.bill_address.lastname, :TransactionId => @data["TransactionID"], :PaymentId => @data["PaymentID"], :amount => @data["Amount"], :order_id => @order.id)

      ebs_payment_method = Spree::PaymentMethod.where(:type => "Spree::PaymentMethod::Ebsin").last
      payment = @order.payments.where(:payment_method_id => ebs_payment_method.id).first
      payment.source = source
      payment.save
      payment.complete!
    end

  end
end

app/views/admin/payments/_list.html.erb
<table class="index">
  <tr>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
    <th><%= t("amount") %></th>
    <th><%= t("payment_method") %></th>
    <th></th>
  </tr>
  <% payments.each do |payment| %>
    <tr>
      <td><%= payment.created_at.to_s(:date_time24) %></td>
      <td><%= number_to_currency(payment.amount) %></td>
      <td><%= payment_method_name payment %></td>
      <td>
				<% unless payment_method_name(payment) == 'Ebsin' %>
        	<%= link_to t('show'), admin_order_payment_path(@order, payment) %>
	        <% payment.actions.each do |action| %>
	          <%= link_to t(action), fire_admin_order_payment_path(@order, payment, :e => action), :method => :put, :confirm => t('are_you_sure') %>
	        <% end %>
	        <%# if payment.actions.empty? and !payment.finalized? %>
	          <%#= link_to t(:finalize), finalize_admin_order_payment_path(@order, payment), :method => :put, :confirm => t('are_you_sure') %>
	        <%# end %>
				<% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/gateway/ebsin/show.html.erb
<fieldset id='payment' style="width:70%;">
  <%= form_tag @gateway.preferred_url do -%>

  <h3 class="heading"><%= t("confirm") %> your order</h3>

  <fieldset id="order_details" style='padding-left:0px;'>
    <div class="clear"></div>
    <p style='text-transform:uppercase;font-weight:bold; margin:0px 0px 10px 0px;'>ORDER NO. <%= @order.number %> (<a href="/checkout/payment" style="font-size: 12px; font-weight:normal;">&larr; Back to payment options</a>)</p>
    <%= render :partial => 'shared/order_details', :locals => {:order => @order} -%>
  </fieldset>

  <hr />
  <p class="tenpx"><%= t('ebsin_instuctional_text') %></p>
  <%= hidden_field_tag 'account_id',      @gateway.preferred_account_id %>
	<%= hidden_field_tag 'reference_no',    @order.number %>
	<%= hidden_field_tag 'amount',          @order.total.to_s %>
  <%= hidden_field_tag 'return_url',      [gateway_ebsin_comeback_url(@order),'DR={DR}'].join('?')  %>
  <%= hidden_field_tag 'secure_hash',     @hash %>
	<%= hidden_field_tag 'name',            @bill_address.firstname %>
	<%= hidden_field_tag 'address',         @bill_address.address1 %>
	<%= hidden_field_tag 'city',            @bill_address.city %>
	<%= hidden_field_tag 'postal_code',     @bill_address.zipcode %>
	<%= hidden_field_tag 'country',         @bill_address.country.iso3 %>
  <%= hidden_field_tag 'description',     "#{Spree::Config[:site_name]} Order: #{@order.number}" %>
  <%= hidden_field_tag 'email',           (@order.email || @order.user.try(:email))  %>

  <%= hidden_field_tag 'mode',            @gateway.preferred_mode %>
  <%= hidden_field_tag 'phone',           @bill_address.phone %>
  <%= hidden_field_tag 'state',           (@bill_address.state.try(:name) || @bill_address.state_name) %>

  <%= hidden_field_tag 'ship_address',    @ship_address.address1 %>
  <%= hidden_field_tag 'ship_city',       @ship_address.city %>
  <%= hidden_field_tag 'ship_country',    @ship_address.country.iso3 %>
  <%= hidden_field_tag 'ship_name',       @ship_address.full_name %>
  <%= hidden_field_tag 'ship_phone',      @ship_address.phone %>
  <%= hidden_field_tag 'ship_postal_code', @ship_address.zipcode %>
  <%= hidden_field_tag 'ship_state',      (@ship_address.state.try(:name) || @ship_address.state_name) %>
  <div class="form-buttons savebutton_properties" style="margin-top:15px;">
	<%= submit_tag t('ebsin_submit') %>
  </div>
  <% end %>
</fieldset>

app/views/spree/admin/payments/_list.html.erb
<table class="index">
  <tr>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
    <th><%= t("amount") %></th>
    <th><%= t("payment_method") %></th>
    <th> Transaction ID </th>
    <th></th>
  </tr>
  <% payments.each do |payment| %>
    <tr>
      <td><%= payment.created_at.to_s(:date_time24) %></td>
      <td><%= number_to_currency(payment.amount) %></td>
      <td><%= payment_method_name payment %></td>
      <td><%= payment.source.TransactionId %></td>

      <td>
				<% unless payment_method_name(payment) == 'Ebsin' %>
        	<%= link_to t('show'), admin_order_payment_path(@order, payment) %>
	        <% payment.actions.each do |action| %>
	          <%= link_to t(action), fire_admin_order_payment_path(@order, payment, :e => action), :method => :put, :confirm => t('are_you_sure') %>
	        <% end %>
	        <%# if payment.actions.empty? and !payment.finalized? %>
	          <%#= link_to t(:finalize), finalize_admin_order_payment_path(@order, payment), :method => :put, :confirm => t('are_you_sure') %>
	        <%# end %>
				<% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/payments/source_views/_ebsin.html.erb
<table class="index">
  <tr>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
    <th><%= t("amount") %></th>
    <th><%= t("payment_method") %></th>
    <th> Name </th>
    <th> TransactionId </th>
    <th> PaymentId </th>
    <th> </th>
  </tr>
    <tr>
      <td><%= payment.created_at.to_s(:date_time24) %></td>
      <td><%= number_to_currency(payment.amount) %></td>
      <td><%= payment_method_name payment %></td>
      <td><%= payment.source.first_name+" "+payment.source.last_name %></td>
      <td><%= payment.source.TransactionId %></td>
      <td><%= payment.source.PaymentId %></td>
      <td>
				<% unless payment_method_name(payment) == 'Ebsin' %>
        	<% payment.actions.each do |action| %>
	          <%= link_to t(action), fire_admin_order_payment_path(@order, payment, :e => action), :method => :put, :confirm => t('are_you_sure') %>
	        <% end %>
	        <%# if payment.actions.empty? and !payment.finalized? %>
	          <%#= link_to t(:finalize), finalize_admin_order_payment_path(@order, payment), :method => :put, :confirm => t('are_you_sure') %>
	        <%# end %>
				<% end %>
      </td>
    </tr>
</table>

app/views/spree/checkout/payment/_ebsin.html.erb
<%= t('ebsin_pay_instructions') %>

app/views/spree/gateway/ebsin/show.html.erb
<fieldset id='payment' style="width:70%;">
  <%= form_tag @gateway.preferred_url do -%>

  <h3 class="heading"><%= t("confirm") %> your order</h3>

  <fieldset id="order_details" style='padding-left:0px;'>
    <div class="clear"></div>
    <p style='text-transform:uppercase;font-weight:bold; margin:0px 0px 10px 0px;'>ORDER NO. <%= @order.number %> (<a href="/checkout/payment" style="font-size: 12px; font-weight:normal;">&larr; Back to payment options</a>)</p>
    <%= render :partial => 'spree/shared/order_details', :locals => {:order => @order} -%>
  </fieldset>

  <hr />
  <p class="tenpx"><%= t('ebsin_instuctional_text') %></p>
  <%= hidden_field_tag 'account_id',      @gateway.preferred_account_id %>
  <%= hidden_field_tag 'reference_no',    @order.number %>
  <%= hidden_field_tag 'amount',          @order.total.to_s %>
  <%= hidden_field_tag 'return_url',      [gateway_ebsin_comeback_url(@order),'DR={DR}'].join('?')  %>
  <%= hidden_field_tag 'secure_hash',     @hash %>
  <%= hidden_field_tag 'name',            @bill_address.firstname %>
  <%= hidden_field_tag 'address',         @bill_address.address1 %>
  <%= hidden_field_tag 'city',            @bill_address.city %>
  <%= hidden_field_tag 'postal_code',     @bill_address.zipcode %>
  <%= hidden_field_tag 'country',         @bill_address.country.iso3 %>
  <%= hidden_field_tag 'description',     "#{Spree::Config[:site_name]} Order: #{@order.number}" %>
  <%= hidden_field_tag 'email',           (@order.email || @order.user.try(:email))  %>

  <%= hidden_field_tag 'mode',            @gateway.preferred_mode %>
  <%= hidden_field_tag 'phone',           @bill_address.phone %>
  <%= hidden_field_tag 'state',           (@bill_address.state.try(:name) || @bill_address.state_name) %>

  <%= hidden_field_tag 'ship_address',    @ship_address.address1 %>
  <%= hidden_field_tag 'ship_city',       @ship_address.city %>
  <%= hidden_field_tag 'ship_country',    @ship_address.country.iso3 %>
  <%= hidden_field_tag 'ship_name',       @ship_address.full_name %>
  <%= hidden_field_tag 'ship_phone',      @ship_address.phone %>
  <%= hidden_field_tag 'ship_postal_code', @ship_address.zipcode %>
  <%= hidden_field_tag 'ship_state',      (@ship_address.state.try(:name) || @ship_address.state_name) %>
  <div class="form-buttons savebutton_properties" style="margin-top:15px;">
  <%= submit_tag t('ebsin_submit') %>
  </div>
  <% end %>
</fieldset>